# Generated by Django 3.1.7 on 2021-03-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-start_date'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
