# Generated by Django 3.1.7 on 2021-03-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20210306_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
        ),
    ]
