# Generated by Django 3.1.7 on 2021-03-07 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20210306_1531'),
        ('items', '0004_auto_20210306_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_items', to='promotions.promotion'),
        ),
    ]
