# Generated by Django 3.1.7 on 2021-03-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Покупателя', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_ordered'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказ'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-date_added'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-date_added'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
